//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int Id { get; set; }
        public string Pickup_date { get; set; }
        public string Dropoff_date { get; set; }
        public int CustomerId { get; set; }
        public int CarId { get; set; }
        public int StoreId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Car Car { get; set; }
        public virtual Store Store { get; set; }
    }
}
